config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pokemons do
    resources :bookings, only: :create
  end

  resources :bookings, only: :destroy do
    member do
      patch :accept
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  enum :status, [ :pending, :accepted, :declined, :canceled ]
  # Scope are called on the Class
  scope :pending, -> { where(status: "pending") }
  scope :accepted, -> { where(status: "accepted") }
  scope :declined, -> { where(status: "declined") }
  scope :canceled, -> { where(status: "canceled") }

  before_validation :set_status

  private

  def set_status
    self.status = "pending"
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord

  # include PokemonConcern
  TYPES = %w[acier combat dragon eau electrik feu fee glace
             insecte normal plante poison psy roche sol spectre tenebres vol]

  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :name, :types, presence: true

  validates :price_per_day, numericality: { only_float: true }

  before_validation :shift_types

  # TODO scope with SQL request

  private

  def shift_types
    types.delete("")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pokemons
  has_many :bookings

  has_many :requested_bookings, through: :pokemons, source: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    raise
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[show edit update destroy]
  def index
    @pokemons = Pokemon.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pokemon.update(pokemon_params)
      redirect_to pokemon_path(@pokemon)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pokemon.destroy
    redirect_to pokemons_path, status: :see_other
  end

  private

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def pokemon_params
    params.require(:pokemon).permit(:name, :price_per_day, :photo, :poster_url, types: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <%= simple_form_for([@pokemon, @booking], data: { controller: "flatpickr" } ) do |f| %>
    <%= f.input :start_date, label: false, as: :string, input_html: { class: "d-none", data: { flatpickr_target: 'startInput' } } %>
    <%= f.input :end_date, label: false, as: :string, input_html: { class: "d-none", data: { flatpickr_target: 'endInput' } } %>
    <%= f.submit 'Book now!', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlatpickrUpdate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner.jpg' %>);">
  <div class="container">
    <h1>PokemonBnB <strong>propose</strong> de <strong>trouver son pokemon</strong>!</h1>
    <p></p>
    <%= link_to "Find your Pokemon now", pokemons_path, class: "btn btn-flat machin" %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div class="cards">
  <% @pokemons.each do |pokemon| %>
    <%= link_to pokemon_path(pokemon) do %>
      <div class="card-trip">
        <img src="<%= pokemon.poster_url %>" />
        <div class="card-trip-infos">
          <div>
            <h2><%= pokemon.name %></h2>
            <p><%= pokemon.types.join(' ') %></p>
          </div>
          <h2 class="card-trip-pricing"><%= pokemon.price_per_day %>€</h2>
          <img src="https://kitt.lewagon.com/placeholder/users/wulfens" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pokemons/new.html.erb
<div class="container">
  <%= simple_form_for @pokemon, html: { data: { controller: "load-image" } } do |f| %>
    <%= f.input :name %>
    <%= f.input :types, collection: Pokemon::TYPES, input_html: {multiple: true, data: {controller: "tom-select", tom_select_options_value: {tags: true, plugins: ['remove_button']}}} %>
    <!-- <%# f.input :poster_url %> -->

    <%# Image tag get filled by the controller load-image %>
    <%= image_tag "", data: {load_image_target: "image" } %>
    <%= f.input :photo, as: :file, input_html: { data: { action: 'change->load-image#displayImage' } } %>
    <%= f.input :price_per_day %>
    <%= f.submit %>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<div>
  <%= @pokemon.name %>
  <%= render "bookings/form" %>
</div>



<%= link_to "Back", pokemons_path %>

<%= link_to "Update", edit_pokemon_path(@pokemon) %>

<%= link_to "Destroy", pokemon_path(@pokemon), data: { turbo_method: :delete } %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "pokeball.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add a Pokemon", new_pokemon_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>